name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # allows manual trigger from GitHub Actions

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./messaging_app
          file: ./messaging_app/Dockerfile
          push: true
          tags: hali674/messaging_app:latest
